### ISSUE TITLE
[web] invoke is not return nothing

### ISSUE THREAD

**Issue by viztushar** [jamiewest/signalr_core#9]
invoke method is not return anything

**Comment by jamiewest** [comment]
There was update since this comment, could you try and let me know if this is still an issue?

**Comment by viztushar** [comment]
still not get any response
in 1.0.4 getting this error
`
(WebSockets transport) sending data. String data of length '366'.
(WebSockets transport) sending data. String data of length '183'.
Error: Exception: Invalid payload for Completion message.
    at Object.throw_ [as throw] (http://localhost:51104/dart_sdk.js:4463:11)
    at json_hub_protocol.JsonHubProtocol.new.[_isCompletionMessage] (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:536:19)
    at json_hub_protocol.JsonHubProtocol.new.parseMessages (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:411:39)
    at hub_connection.HubConnection.new.[_processIncomingData] (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:1654:41)
    at web_socket_transport.WebSocketTransport.new.<anonymous> (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:1938:77)
    at http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:2087:20
    at _RootZone.runUnaryGuarded (http://localhost:51104/dart_sdk.js:36955:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:51104/dart_sdk.js:30667:22)
    at _ControllerSubscription.new.[_add] (http://localhost:51104/dart_sdk.js:30613:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:51104/dart_sdk.js:33554:34)
    at _SyncStreamController.new.[_add] (http://localhost:51104/dart_sdk.js:33362:26)
    at _SyncStreamController.new.add (http://localhost:51104/dart_sdk.js:33327:19)
    at _RootZone.runUnaryGuarded (http://localhost:51104/dart_sdk.js:36955:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:51104/dart_sdk.js:30667:22)
    at _ControllerSubscription.new.[_add] (http://localhost:51104/dart_sdk.js:30613:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:51104/dart_sdk.js:33554:34)
    at _SyncStreamController.new.[_add] (http://localhost:51104/dart_sdk.js:33362:26)
    at _SyncStreamController.new.add (http://localhost:51104/dart_sdk.js:33327:19)
    at _StreamSinkWrapper.new.add (http://localhost:51104/dart_sdk.js:33664:24)
    at _GuaranteeSink.new.add (http://localhost:51104/packages/stream_channel/src/stream_channel_controller.dart.lib.js:1026:24)
    at http://localhost:51104/packages/web_socket_channel/html.dart.lib.js:204:36
    at Object._checkAndCall (http://localhost:51104/dart_sdk.js:4673:16)
    at Object.dcall (http://localhost:51104/dart_sdk.js:4678:17)
    at WebSocket.<anonymous> (http://localhost:51104/dart_sdk.js:104624:21)Error: Exception: Invalid payload for Completion message.
    at Object.throw_ [as throw] (http://localhost:51104/dart_sdk.js:4463:11)
    at json_hub_protocol.JsonHubProtocol.new.[_isCompletionMessage] (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:536:19)
    at json_hub_protocol.JsonHubProtocol.new.parseMessages (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:411:39)
    at hub_connection.HubConnection.new.[_processIncomingData] (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:1654:41)
    at web_socket_transport.WebSocketTransport.new.<anonymous> (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:1938:77)
    at http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:2087:20
    at _RootZone.runUnaryGuarded (http://localhost:51104/dart_sdk.js:36955:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:51104/dart_sdk.js:30667:22)
    at _ControllerSubscription.new.[_add] (http://localhost:51104/dart_sdk.js:30613:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:51104/dart_sdk.js:33554:34)
    at _SyncStreamController.new.[_add] (http://localhost:51104/dart_sdk.js:33362:26)
    at _SyncStreamController.new.add (http://localhost:51104/dart_sdk.js:33327:19)
    at _RootZone.runUnaryGuarded (http://localhost:51104/dart_sdk.js:36955:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:51104/dart_sdk.js:30667:22)
    at _ControllerSubscription.new.[_add] (http://localhost:51104/dart_sdk.js:30613:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:51104/dart_sdk.js:33554:34)
    at _SyncStreamController.new.[_add] (http://localhost:51104/dart_sdk.js:33362:26)
    at _SyncStreamController.new.add (http://localhost:51104/dart_sdk.js:33327:19)
    at _StreamSinkWrapper.new.add (http://localhost:51104/dart_sdk.js:33664:24)
    at _GuaranteeSink.new.add (http://localhost:51104/packages/stream_channel/src/stream_channel_controller.dart.lib.js:1026:24)
    at http://localhost:51104/packages/web_socket_channel/html.dart.lib.js:204:36
    at Object._checkAndCall (http://localhost:51104/dart_sdk.js:4673:16)
    at Object.dcall (http://localhost:51104/dart_sdk.js:4678:17)
    at WebSocket.<anonymous> (http://localhost:51104/dart_sdk.js:104624:21)Error: Exception: Invalid payload for Completion message.
    at Object.throw_ [as throw] (http://localhost:51104/dart_sdk.js:4463:11)
    at json_hub_protocol.JsonHubProtocol.new.[_isCompletionMessage] (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:536:19)
    at json_hub_protocol.JsonHubProtocol.new.parseMessages (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:411:39)
    at hub_connection.HubConnection.new.[_processIncomingData] (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:1654:41)
    at web_socket_transport.WebSocketTransport.new.<anonymous> (http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:1938:77)
    at http://localhost:51104/packages/signalr_core/src/json_hub_protocol.dart.lib.js:2087:20
    at _RootZone.runUnaryGuarded (http://localhost:51104/dart_sdk.js:36955:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:51104/dart_sdk.js:30667:22)
    at _ControllerSubscription.new.[_add] (http://localhost:51104/dart_sdk.js:30613:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:51104/dart_sdk.js:33554:34)
    at _SyncStreamController.new.[_add] (http://localhost:51104/dart_sdk.js:33362:26)
    at _SyncStreamController.new.add (http://localhost:51104/dart_sdk.js:33327:19)
    at _RootZone.runUnaryGuarded (http://localhost:51104/dart_sdk.js:36955:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:51104/dart_sdk.js:30667:22)
    at _ControllerSubscription.new.[_add] (http://localhost:51104/dart_sdk.js:30613:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:51104/dart_sdk.js:33554:34)
    at _SyncStreamController.new.[_add] (http://localhost:51104/dart_sdk.js:33362:26)
    at _SyncStreamController.new.add (http://localhost:51104/dart_sdk.js:33327:19)
    at _StreamSinkWrapper.new.add (http://localhost:51104/dart_sdk.js:33664:24)
    at _GuaranteeSink.new.add (http://localhost:51104/packages/stream_channel/src/stream_channel_controller.dart.lib.js:1026:24)
    at http://localhost:51104/packages/web_socket_channel/html.dart.lib.js:204:36
    at Object._checkAndCall (http://localhost:51104/dart_sdk.js:4673:16)
    at Object.dcall (http://localhost:51104/dart_sdk.js:4678:17)
    at WebSocket.<anonymous> (http://localhost:51104/dart_sdk.js:104624:21)(WebSockets transport) sending data. String data of length '117'.
Application finished.
Exited (sigterm)
`
